export const LOGIN_SUCCESS = 'LOGIN__SUCCESS';
export const LOGIN_FAILURE = 'LOGIN__FAILURE';

export const SET_COOKIE = 'SET_COOKIE';
export const REMOVE_COOKIE = 'REMOVE_COOKIE';

export const LOGOUT__REQUEST = 'LOGOUT__REQUEST';
export const LOGOUT__SUCCESS = 'LOGOUT__SUCCESS';
export const LOGOUT__FAILURE = 'LOGOUT__FAILURE';

export const CREATE_ACCOUNT__REQUEST = 'CREATE_ACCOUNT__REQUEST';
export const CREATE_ACCOUNT__SUCCESS = 'CREATE_ACCOUNT__SUCCESS';
export const CREATE_ACCOUNT__FAILURE = 'CREATE_ACCOUNT__FAILURE';

export const GET_PROFILE__REQUEST = 'GET_PROFILE__REQUEST';
export const GET_PROFILE__SUCCESS = 'GET_PROFILE__SUCCESS';
export const GET_PROFILE__FAILURE = 'GET_PROFILE__FAILURE';

export const UPDATE_PROFILE__REQUEST = 'UPDATE_PROFILE__REQUEST';
export const UPDATE_PROFILE__SUCCESS = 'UPDATE_PROFILE__SUCCESS';
export const UPDATE_PROFILE__FAILURE = 'UPDATE_PROFILE__FAILURE';

export const DELETE_PROFILE__REQUEST = 'DELETE_PROFILE__REQUEST';
export const DELETE_PROFILE__SUCCESS = 'DELETE_PROFILE__SUCCESS';
export const DELETE_PROFILE__FAILURE = 'DELETE_PROFILE__FAILURE';
